# Generated by Django 3.2.6 on 2021-11-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='following_user_id',
        ),
    ]
