# Generated by Django 3.2.6 on 2021-11-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_followerscount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowersCount',
            new_name='Followers',
        ),
    ]
