# Generated by Django 3.2.6 on 2021-11-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_rename_followerscount_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
