# Generated by Django 3.2.6 on 2021-11-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_userfollowing_following_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user_id', 'following_user_id')},
        ),
    ]
