# Generated by Django 3.2.6 on 2021-11-30 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_like_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='liking', to=settings.AUTH_USER_MODEL),
        ),
    ]
