# Generated by Django 3.2.6 on 2021-11-30 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20211130_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
